### ISSUE TITLE
好像只支持文本，不支持html元素的吗

### ISSUE THREAD

**Issue by adoin** [ruofee/vue-ellipsis-3#2]

**Comment by ruofee** [comment]
设置 `useInnerHtml ` 属性为 `true`，就会将 `text` 作为 HTML 传入，具体可以参考：http://vue-ellipsis.ruofee.cn/usage/#%E5%AF%8C%E6%96%87%E6%9C%AC%E7%BC%A9%E7%95%A5

**Comment by ruofee** [comment]
没其他问题的话我先关闭 issue 啦~

**Comment by adoin** [comment]
好的
&nbsp;


adoin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月16日(星期一) 上午10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ruofee/vue-ellipsis-3] 好像只支持文本，不支持html元素的吗 (Issue #2)





 
Closed #2 as completed.
 
&mdash;
