### ISSUE TITLE
我想利用这个组件做个展开收起功能发现2个问题

### ISSUE THREAD

**Issue by aimm** [ruofee/vue-ellipsis-3#3]
1. 文本中带换行符，并且设置使用 html 形式渲染，初始收起状态，展开后换行符无效了
2. 展开后 展开收起 插槽内容就不显示了

因为时间原因，简单修改了 JsEllipsis.vue 的 reflow 方法

![0CB70F~1](https://github.com/user-attachments/assets/78ae8dca-794a-42b6-af46-5332d2a25ff8)
![F02295~1](https://github.com/user-attachments/assets/c7a03265-244c-404e-9d5b-63a86a7488f9)

**Comment by ruofee** [comment]
@aimm 你描述的应该都是一个问题吧：展开缩略文本之后“收起”按钮就不展示了。这是符合预期的效果，因为 ellipsisNode 插槽是缩略节点的意思，只作用于缩略状态（“展开”按钮）。
目前有两个解决方案：
**第一种**：将“展开”和“收起”按钮写到 vue-ellipsis-3 组件外面，如下：
```html
<vue-ellipsis-3 :ellipsis="ellipsis" />
<div>{{ ellipsis ? '展开' : '收起' }}</div>
```
这种方案可以直接使用，但缩略按钮会独占一行。

**第二种**：缩略组件的 vue 2.x 版本中有人提了一个相同的 issue：https://github.com/ruofee/vue-ellipsis-component/issues/15
最终是新增了一个 unellipsisNode 插槽，这个方案似乎更好一些。

**Comment by ruofee** [comment]
@aimm 可以安装最新版本：0.0.7，使用 unellipsisNode slot 或是 unellipsisNode props，配合点击事件 onUnellipsisClick 使用，具体可以查看文档：http://vue-ellipsis.ruofee.cn/api/#props

**Comment by ruofee** [comment]
issue 先关闭了，有使用问题可以重新找我
