### ISSUE TITLE
换行符表现不一致

### ISSUE THREAD

**Issue by Cat1007** [ruofee/vue-ellipsis-3#4]
文本中存在 \n 作为换行符

不使用 useInnerHtml 时：
折叠状态下，换行符失效，变成不换行的文本
展开状态下，换行符变为 `<br/>`， 换行符合预期

留意到一个 issue https://github.com/ruofee/vue-ellipsis-3/issues/3

使用 useInnerHtml 试验时
折叠状态下，换行符变为 `<br/>` ，换行符合预期
展开状态下，换行符失效，变成不换行的文本

**Comment by ruofee** [comment]
根据你提供的信息，我找到了问题所在，实际上就是在截取过程中使用 textContent 获取文本内容的时候丢失了 `\n`，对此做了修改，以文本“这是非常非常\n非常非常长的文本”为例子，最终效果如下：

**当不使用 useInnerHtml 时**

展开状态为：

```
这是非常非常
非常非常长的文本
```

折叠状态为：

```
这是非常非常
非常非常长...
```

**当使用 useInnerHtml 时**

展开状态为：

```
这是非常非常 非常非常长的文本
```

折叠状态为：

```
这是非常非常 非常非常...
```

其中设置 useInnerHtml 的情况下，`\n` 会被转换成空格，这符合 Web 标准，如果需要换行，可以自行转成 `<br>`。

可以安装 0.0.8 版本尝试！谢谢你提供的信息！

**Comment by Cat1007** [comment]
0.0.8试验后ok，自己排查也发现是textContent和innerText的一些差异导致的，没想到大佬修这么快
